# Generated by Django 5.0 on initial schema generation

import apps.documents.models
from django.conf import settings
from django.db import models,migrations
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(name='Document',
                               fields=[
                                   ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
                                   ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.documents.models.document_file_path)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(
                    choices=[
                        ('PENDING', 'Pending'),
                        ('PROCESSING', 'Processing'),
                        ('COMPLETED', 'Completed'),
                        ('FAILED', 'Failed')

                               ],
                               default= 'PENDING',
                               max_length =20
                            )),
                            ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='documents',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField()),
                ('key_takeaways', models.JSONField(default=list)),
                ('topics', models.JSONField(default=list)),
                ('sentiment', models.CharField(default='NEUTRAL', max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='insight',
                    to='documents.document'
                )),
            ],
        ),

    ]